version: "3"

services:
  backoffice-service-amichelena:
    container_name: backoffice-service-amichelena
    networks:
      - amichelena-backend
    build:
      context: .
      dockerfile: Dockerfile
    #command: sh -c 'npm run build; npm run start'
    ports:
      - "3102:3102"
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
    env_file:
      - ./.env

volumes:
  node-modules:

networks:
  amichelena-backend:
    driver: bridge
  default:
    external:
      name: amichelena
